[phases.setup]
nixPkgs = ["python312"]

[phases.build]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn config.wsgi:logistics --bind 0.0.0.0:$PORT"
