# Generated by Django 4.2.23 on 2025-07-11 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InvoiceRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.CharField(
                        choices=[
                            ("brenger", "Brenger"),
                            ("libero", "Libero"),
                            ("swdevries", "Sw De Vries"),
                            ("transpoksi", "Transpoksi"),
                            ("wuunder", "Wuunder"),
                            ("magic_movers", "Magic Movers"),
                            ("tadde", "Tadde"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "delta_sum",
                    models.FloatField(help_text="Sum of all Delta values for this run"),
                ),
                (
                    "parsed_ok",
                    models.BooleanField(help_text="True if parsing succeeded"),
                ),
                (
                    "num_rows",
                    models.IntegerField(help_text="Number of invoice lines processed"),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_creation_date",
                    models.DateTimeField(help_text="Order creation timestamp"),
                ),
                (
                    "order_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Order ID"
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "route",
                    models.CharField(
                        max_length=31, verbose_name="buyer_country-seller_country"
                    ),
                ),
                ("category_lvl_1_and_2", models.CharField(max_length=100)),
                ("category_lvl_2_and_3", models.CharField(max_length=100)),
                (
                    "price_expected",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expected price from internal CMS",
                        max_digits=12,
                        verbose_name="price",
                    ),
                ),
                (
                    "price_brenger",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_libero",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_swdevries",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_transpoksi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_wuunder",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_magic_movers",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_tadde",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "delta",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual minus expected",
                        max_digits=12,
                        verbose_name="Delta",
                    ),
                ),
                (
                    "delta_sum",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total delta for parent run",
                        max_digits=14,
                        verbose_name="Delta_sum",
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="Invoice date")),
                ("invoice_number", models.CharField(db_index=True, max_length=100)),
                (
                    "run",
                    models.ForeignKey(
                        help_text="Parent InvoiceRun",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="logistics.invoicerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-run__timestamp", "order_creation_date"],
                "indexes": [
                    models.Index(
                        fields=["order_id"], name="logistics_i_order_i_4a3e70_idx"
                    ),
                    models.Index(
                        fields=["invoice_number"], name="logistics_i_invoice_1b4bcd_idx"
                    ),
                ],
            },
        ),
    ]
