# Generated by Django 4.2.23 on 2025-07-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoiceline",
            options={
                "ordering": ["-run__timestamp", "order_creation_date"],
                "verbose_name": "Invoice Line",
                "verbose_name_plural": "Invoice Lines",
            },
        ),
        migrations.AlterModelOptions(
            name="invoicerun",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Invoice Run",
                "verbose_name_plural": "Invoice Runs",
            },
        ),
        migrations.AddField(
            model_name="invoicerun",
            name="invoice_number",
            field=models.CharField(db_index=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="invoicerun",
            unique_together={("partner", "invoice_number")},
        ),
    ]
