# Generated by Django 4.2.23 on 2025-07-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "logistics",
            "0002_alter_invoiceline_options_alter_invoicerun_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invoicerun",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="invoicerun",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Invoice number (empty for legacy or unparsed runs)",
                max_length=100,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicerun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_number", ""), _negated=True),
                fields=("partner", "invoice_number"),
                name="unique_partner_invoice_number_nonempty",
            ),
        ),
    ]
